#!/usr/bin/env Rscript

# Function that takes many fpkm matrix table typically generated
# by the cufflinks and merge them. Directory structure has to 
# follow something like this. /path/to/specified/outdir/<sampleName>
# Then in that directory you have a file called genes.fpkm_tracking
# (generated by cufflinks).
# Author: Julien Tremblay - julien.tremblay@mail.mcgill.ca
mergeTables <- function(design, indir, outfile) {

  options(stringsAsFactors = FALSE)
  
  tDataDesign = read.table(design, sep="\t", header=T)
  
  df = NULL
  names = NULL
  
  sampleNames = as.character(as.vector(tDataDesign[,1]))
  for(i in 1:length(sampleNames) ){
    
    # If file exists, sort it by 1st col. and  cbind fpkm
    sampleNameFolder = paste(indir, sampleNames[i], sep="/")
    currFPKMs        = paste0(sampleNameFolder, "/genes.fpkm_tracking")
    
    print(paste0(sampleNames[i]," : ",currFPKMs ))
    
    if(file.exists(sampleNameFolder)) {
      print(paste0("Folder for sample ", sampleNames[i], " exists..."))
      tDataFPKM       = read.table(currFPKMs, sep="\t", header=T)
      tDataFPKMSorted = tDataFPKM[order(tDataFPKM$tracking_id),]
      
      if(i == 1){ # Add first column one time only.
        df = cbind(df, tDataFPKMSorted$tracking_id)
        df = cbind(df, tDataFPKMSorted$gene_short_name)

        print(head(tDataFPKMSorted$tracking_id))
        print(head(tDataFPKMSorted$gene_short_name))

        names = append(names, "tracking_id")
        names = append(names, "gene_short_name")
      }
      
      df = cbind(df, tDataFPKMSorted$FPKM)
      names = append(names, sampleNames[i])
      
    }
  }
  df = data.frame(df)
  names(df) = names

  df$tracking_id = as.character(df$tracking)
  
  write.table(df, file=outfile, sep="\t", quote=FALSE, row.names=FALSE)
  
  print("Done merging FPKMs...")
  
} 

usage=function(errM) {
  cat("\nUsage : Rscript mergeFPKMs.R [option] <Value>\n")
  cat("       -i        : Indir\n")
  cat("       -d        : design file (mugqic RNASeq pipeline template)\n")
  cat("       -o        : outfile\n")
}

ARG = commandArgs(trailingOnly = T)

if(length(ARG) < 2) {
  usage("missing arguments")
}

## get arg variables
for (i in 1:length(ARG)) {
  if (ARG[i] == "-i") {
    indir=ARG[i+1]
  } else if (ARG[i] == "-o") {
    outfile=ARG[i+1]
  }else if (ARG[i] == "-d") {
    design=ARG[i+1]
  }
}

mergeTables(design, indir, outfile)

